// The build-1 trait catalog (docs/TRAITS.md §3, §5) in rung order. Trait effects are the tier
// tables in trait-modifiers.ts; no system ever switches on a trait id. `TraitId` (types/game.ts)
// is derived from these rows, so the rows are checked against `TraitCatalogRow` (plain string
// ids) and the pure catalog test pins that every `requires` id is a row.

import { BACTERIUM_VARIANT, CELL_STAGE, DNA_TAG, type TraitId } from '../types/game.js';
import { SOUND_EVENT } from '../types/audio.js';
import { TRAIT_CATEGORY, TRAIT_RARITY, type TraitCatalogRow, type TraitTiers } from '../types/traits.js';
import { ENDOSYMBIOSIS_BACTERIA_REQUIRED } from './ladder.js';
import * as tiers from './trait-modifiers.js';

export { DEFAULT_CELL_MODIFIERS, SPRINT_COOLDOWN_FLOOR_SECONDS } from './trait-modifiers.js';

export const TRAIT_TIER_COUNT = 3;

/** `primary_locomotion` has no build-1 member (docs/TRAITS.md §3.17). */
export const EXCLUSION_GROUPS = ['body_plan', 'membrane', 'primary_locomotion'] as const;

const BODY_PLAN = EXCLUSION_GROUPS[0];
const MEMBRANE = EXCLUSION_GROUPS[1];

export const TRAIT_CATALOG = [
  {
    id: 'nucleoid',
    name: 'Nucleoid Coil',
    stage: CELL_STAGE.protocell,
    requires: [],
    category: TRAIT_CATEGORY.genome,
    rarity: TRAIT_RARITY.common,
    tags: [DNA_TAG.metabolic],
    tiers: tiers.NUCLEOID_TIERS,
    visual: 'a loose, brighter tangle of thread in the cytoplasm with no boundary; 1 / 2 / 3 loops',
    audioCue: SOUND_EVENT.softClick,
  },
  {
    id: 'simple_flagellum',
    name: 'Simple Flagellum',
    stage: CELL_STAGE.protocell,
    requires: [],
    category: TRAIT_CATEGORY.locomotion,
    rarity: TRAIT_RARITY.uncommon,
    tags: [DNA_TAG.motile, DNA_TAG.predatory],
    tiers: tiers.SIMPLE_FLAGELLUM_TIERS,
    visual:
      'one long tail trailing opposite the velocity, sine amplitude growing per tier; tier III adds a second tail',
    audioCue: SOUND_EVENT.whipCrack,
  },
  {
    id: 'cell_wall',
    name: 'Cell Wall',
    stage: CELL_STAGE.protocell,
    requires: [],
    category: TRAIT_CATEGORY.membrane,
    rarity: TRAIT_RARITY.common,
    tags: [DNA_TAG.armored],
    exclusionGroup: MEMBRANE,
    tiers: tiers.CELL_WALL_TIERS,
    visual: 'a second, brighter rim inside the first; rim thickness × 1.5 / 2 / 2.5',
    audioCue: SOUND_EVENT.dullThud,
  },
  {
    id: 'ribosomes',
    name: 'Ribosome Studs',
    stage: CELL_STAGE.prokaryote,
    requires: [],
    category: TRAIT_CATEGORY.metabolism,
    rarity: TRAIT_RARITY.common,
    tags: [DNA_TAG.metabolic],
    tiers: tiers.RIBOSOMES_TIERS,
    visual: 'a fine stipple of dots along the inside of the membrane, density per tier',
    audioCue: SOUND_EVENT.eatGurgle,
  },
  {
    id: 'mitochondrion',
    name: 'Mitochondrion',
    stage: CELL_STAGE.prokaryote,
    requires: [],
    unlockedBy: { bacteriumVariant: BACTERIUM_VARIANT.aerobic, count: ENDOSYMBIOSIS_BACTERIA_REQUIRED },
    category: TRAIT_CATEGORY.metabolism,
    rarity: TRAIT_RARITY.uncommon,
    tags: [DNA_TAG.metabolic],
    tiers: tiers.MITOCHONDRION_TIERS,
    visual: '1 / 2 / 3 orange-red beans with inner folds, pulsing on sprint',
    audioCue: SOUND_EVENT.lowThrum,
  },
  {
    id: 'chloroplast',
    name: 'Chloroplast',
    stage: CELL_STAGE.prokaryote,
    requires: [],
    unlockedBy: { bacteriumVariant: BACTERIUM_VARIANT.photosynthetic, count: ENDOSYMBIOSIS_BACTERIA_REQUIRED },
    category: TRAIT_CATEGORY.metabolism,
    rarity: TRAIT_RARITY.common,
    tags: [DNA_TAG.photic],
    tiers: tiers.CHLOROPLAST_TIERS,
    visual: '1 / 2 / 3 green lenses of 6 granules, membrane tinted green, brighter inside the shallows',
    audioCue: SOUND_EVENT.warmShimmer,
  },
  {
    id: 'nuclear_envelope',
    name: 'Nuclear Envelope',
    stage: CELL_STAGE.endosymbiosis,
    requires: ['nucleoid'],
    category: TRAIT_CATEGORY.genome,
    rarity: TRAIT_RARITY.common,
    tags: [DNA_TAG.armored, DNA_TAG.metabolic],
    tiers: tiers.NUCLEAR_ENVELOPE_TIERS,
    visual: 'the nucleoid thread gathers into a bounded round nucleus with its own rim; rim brightness per tier',
    audioCue: SOUND_EVENT.deepChime,
  },
  {
    id: 'cytoskeleton',
    name: 'Cytoskeleton Lattice',
    stage: CELL_STAGE.eukaryote,
    requires: [],
    category: TRAIT_CATEGORY.locomotion,
    rarity: TRAIT_RARITY.common,
    tags: [DNA_TAG.motile, DNA_TAG.armored],
    tiers: tiers.CYTOSKELETON_TIERS,
    visual: 'the membrane wobble tightens to a taut outline, sharper contact dents, a faint lattice under the membrane',
    audioCue: SOUND_EVENT.tautSnap,
  },
  {
    id: 'cilia',
    name: 'Cilia Fringe',
    stage: CELL_STAGE.eukaryote,
    requires: [],
    category: TRAIT_CATEGORY.locomotion,
    rarity: TRAIT_RARITY.common,
    tags: [DNA_TAG.motile],
    tiers: tiers.CILIA_TIERS,
    visual: 'a ring of 24 / 36 / 48 short hairs on the rim beating in a travelling wave that follows velocity',
    audioCue: SOUND_EVENT.softFlutter,
  },
  {
    id: 'food_vacuole',
    name: 'Food Vacuole',
    stage: CELL_STAGE.eukaryote,
    requires: [],
    category: TRAIT_CATEGORY.metabolism,
    rarity: TRAIT_RARITY.uncommon,
    tags: [DNA_TAG.metabolic, DNA_TAG.predatory],
    tiers: tiers.FOOD_VACUOLE_TIERS,
    visual: '2 / 3 / 4 bubbling orange digestive vacuoles; prey dissolves visibly faster',
    audioCue: SOUND_EVENT.absorbGurgle,
  },
  {
    id: 'toxin_vacuole',
    name: 'Toxin Vacuole',
    stage: CELL_STAGE.eukaryote,
    requires: [],
    category: TRAIT_CATEGORY.offense,
    rarity: TRAIT_RARITY.rare,
    tags: [DNA_TAG.toxic],
    tiers: tiers.TOXIN_VACUOLE_TIERS,
    visual: 'one large violet vacuole pulsing near the nucleus',
    audioCue: SOUND_EVENT.toxinHiss,
  },
  {
    id: 'amoeba_pseudopods',
    name: 'Amoeba Pseudopods',
    stage: CELL_STAGE.eukaryote,
    requires: ['cytoskeleton'],
    category: TRAIT_CATEGORY.form,
    rarity: TRAIT_RARITY.uncommon,
    tags: [DNA_TAG.predatory, DNA_TAG.motile],
    exclusionGroup: BODY_PLAN,
    tiers: tiers.AMOEBA_PSEUDOPODS_TIERS,
    visual: 'the membrane extrudes 2 / 3 / 4 blunt lobes toward the velocity and any engulfed prey; irregular blob',
    audioCue: SOUND_EVENT.wetStretch,
  },
  {
    id: 'paramecium_cilia',
    name: 'Paramecium Cilia',
    stage: CELL_STAGE.eukaryote,
    requires: ['cilia'],
    category: TRAIT_CATEGORY.form,
    rarity: TRAIT_RARITY.uncommon,
    tags: [DNA_TAG.motile],
    exclusionGroup: BODY_PLAN,
    tiers: tiers.PARAMECIUM_CILIA_TIERS,
    visual: 'a slipper (aspect 1.6 / 1.8 / 2.0) fully covered in beating cilia, with an oral groove',
    audioCue: SOUND_EVENT.rapidFlutter,
  },
  {
    id: 'euglena_eyespot',
    name: 'Euglena Eyespot',
    stage: CELL_STAGE.eukaryote,
    requires: ['chloroplast'],
    category: TRAIT_CATEGORY.form,
    rarity: TRAIT_RARITY.rare,
    tags: [DNA_TAG.sensory, DNA_TAG.photic],
    exclusionGroup: BODY_PLAN,
    tiers: tiers.EUGLENA_EYESPOT_TIERS,
    visual: 'a red eyespot at the front, a long leading flagellum, green body; spindle with a red dot',
    audioCue: SOUND_EVENT.lowHum,
  },
  {
    id: 'diatom_shell',
    name: 'Diatom Shell',
    stage: CELL_STAGE.eukaryote,
    requires: ['cell_wall'],
    category: TRAIT_CATEGORY.form,
    rarity: TRAIT_RARITY.uncommon,
    tags: [DNA_TAG.armored],
    exclusionGroup: BODY_PLAN,
    tiers: tiers.DIATOM_SHELL_TIERS,
    visual: 'a geometric glassy shell with 8 / 12 / 16 bright-tipped radial spines; star',
    audioCue: SOUND_EVENT.shellScrape,
  },
  {
    id: 'stentor_trumpet',
    name: 'Stentor Trumpet',
    stage: CELL_STAGE.eukaryote,
    requires: ['toxin_vacuole'],
    category: TRAIT_CATEGORY.form,
    rarity: TRAIT_RARITY.rare,
    tags: [DNA_TAG.toxic, DNA_TAG.metabolic],
    exclusionGroup: BODY_PLAN,
    tiers: tiers.STENTOR_TRUMPET_TIERS,
    visual: 'a flared trumpet body with a ciliated rim and a faint violet haze to the aura range',
    audioCue: SOUND_EVENT.hissDrone,
  },
] as const satisfies readonly TraitCatalogRow[];

/** The tier tables keyed by id (`TRAIT_TIERS.cilia[0]`), derived from the catalog so the two cannot drift. */
export const TRAIT_TIERS = Object.fromEntries(TRAIT_CATALOG.map((trait) => [trait.id, trait.tiers])) as Record<
  TraitId,
  TraitTiers
>;

/** Ids reserved for later traits (docs/TRAITS.md §4): never in the catalog, never offered in build 1. */
export const RESERVED_TRAIT_IDS = [
  'jet_siphon',
  'sticky_coat',
  'glass_membrane',
  'fat_vacuole',
  'iron_gut',
  'wide_eyespot',
  'chemotaxis_trails',
  'enzyme_cloud',
  'lunge_reflex',
  'regenerative_cytoplasm',
  'emergency_fission',
  'decoy_vacuole',
  'split_nucleus',
  'bond_filaments',
  'specialisation_node',
  'colony_chorus',
] as const;
