import { Component, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import {
  DEFAULT_PLAYERS_PER_GAME,
  GAME_MODE,
  MAX_PLAYERS_PER_GAME,
  MIN_PLAYERS_PER_GAME,
  ROUND_DURATION_MAX_SECONDS,
  ROUND_DURATION_MIN_SECONDS,
  ROUND_DURATION_SECONDS,
  ROUND_END_CONDITION,
  SEED_MAX,
} from '@evolution/shared';
import type { GameSessionConfig } from '@evolution/shared';
import { GameHostComponent } from './game/game-host.component';
import { RenderBenchComponent } from './game/render/bench/render-bench.component';
import { isBenchRoute } from './game/render/bench/bench-session';
import { MultiplayerService } from './services/multiplayer.service';

/**
 * Minimal, GAME-AGNOSTIC lobby / connection UI stub.
 *
 * It exercises the full multiplayer plumbing — connect, join lobby, create /
 * join / start a game, and view the live room state + latest snapshot JSON —
 * without implementing any specific game. The marked TODO(game) area is where the
 * real game canvas/board mounts (see `game/game-setup.ts`); the create form of
 * docs/UI.md §2 replaces this stub (#30).
 */
@Component({
  selector: 'app-root',
  standalone: true,
  imports: [FormsModule, GameHostComponent, RenderBenchComponent],
  templateUrl: './app.component.html',
  styleUrl: './app.component.css',
})
export class AppComponent {
  readonly title = 'Evolution';

  /** The create form's input bounds: the server schema's, so an out-of-range value is refused here first. */
  readonly bounds = {
    minPlayers: MIN_PLAYERS_PER_GAME,
    maxPlayers: MAX_PLAYERS_PER_GAME,
    roundMinSeconds: ROUND_DURATION_MIN_SECONDS,
    roundMaxSeconds: ROUND_DURATION_MAX_SECONDS,
    seedMax: SEED_MAX,
  } as const;

  readonly multiplayer = inject(MultiplayerService);

  /** `/?bench=<seed>&tick=<n>&zoom=<z>` renders the fixed-seed bench scene instead of the lobby (docs/RENDERING.md §7). */
  readonly isBenchRoute = isBenchRoute(window.location.search);

  // Local lobby form state.
  readonly playerName = signal('Player');
  readonly newGameName = signal('New Game');
  readonly maxPlayers = signal(DEFAULT_PLAYERS_PER_GAME);
  readonly roundDurationSeconds = signal(ROUND_DURATION_SECONDS);
  readonly seed = signal(drawSeed());

  connect(): void {
    this.multiplayer.connect();
    // Immediately announce ourselves to the lobby (queued until the WS opens).
    this.multiplayer.joinLobby(this.playerName(), 0);
  }

  disconnect(): void {
    this.multiplayer.disconnect();
  }

  newSeed(): void {
    this.seed.set(drawSeed());
  }

  createGame(): void {
    this.multiplayer.createGame(this.newGameName(), this.sessionConfig());
  }

  joinGame(id: string): void {
    this.multiplayer.joinGame(id);
  }

  startGame(id: string): void {
    this.multiplayer.startGame(id);
  }

  deleteGame(id: string): void {
    this.multiplayer.deleteGame(id);
  }

  /** Mode and end condition are fixed in build 1 and not shown (docs/UI.md §2). */
  private sessionConfig(): GameSessionConfig {
    return {
      maxPlayers: this.maxPlayers(),
      seed: this.seed(),
      mode: GAME_MODE.freeForAll,
      roundDurationSeconds: this.roundDurationSeconds(),
      endCondition: ROUND_END_CONDITION.timer,
    };
  }
}

/**
 * The round seed is generated by the creating client, never by the server
 * (docs/ARCHITECTURE.md §4). It is the one root the seeded streams grow from, so it is the one
 * place entropy enters. An unsigned 32-bit read is exactly the `0 .. SEED_MAX` range (pinned
 * in session.test.ts), so nothing is clamped here.
 */
function drawSeed(): number {
  const bytes = crypto.getRandomValues(new Uint8Array(Uint32Array.BYTES_PER_ELEMENT));
  return new DataView(bytes.buffer).getUint32(0);
}
