// Client <-> server message envelope (the wire contract, docs/ARCHITECTURE.md §4).
//
// The transport, lobby, room lifecycle and MCP plumbing are game-agnostic. The three game seams
// (`GameInput`, `GameSessionConfig`, `GameSnapshot`) are declared here, their views in `game.ts`,
// and the design docs own the meaning of every field. The server validates every inbound message
// in `ws/message-schemas.ts` before a handler sees it.

import type { EntityId, PlayerId, GameId } from './common.js';
import type {
  CellView,
  DnaFragmentView,
  FoodMoteView,
  GameMode,
  GelPatchView,
  LeaderboardRow,
  MotePositionView,
  PlayerProgressView,
  RoundEndCondition,
  RoundPhase,
  TraitChoiceInput,
} from './game.js';
import type { GameEffect } from './effects.js';
import type { BalanceConfig } from '../constants/balance.js';

// ===== The game seams =====

/** One per client tick, coalesced by the server (docs/ARCHITECTURE.md §3.2). */
export interface GameInput {
  /** Monotonic per client, one per client tick; echoed back for prediction (§5). */
  sequence: number;
  /** Pointer target in world units. */
  targetX: number;
  targetY: number;
  /** Edge-triggered by the client: start a sprint this tick if the cooldown allows. */
  shouldSprint: boolean;
  traitChoice: TraitChoiceInput | null;
  /** Reserved for build 2: validated and ignored (docs/GAME-DESIGN.md §11). */
  shouldSplit?: boolean;
  shouldEject?: boolean;
}

export interface GameSessionConfig {
  /** MIN_PLAYERS_PER_GAME .. MAX_PLAYERS_PER_GAME. */
  maxPlayers: number;
  /** 0 .. SEED_MAX; generated by the creating client, never by the server. */
  seed: number;
  /** `colony` is rejected by the schema until build 2. */
  mode: GameMode;
  /** ROUND_DURATION_MIN_SECONDS .. ROUND_DURATION_MAX_SECONDS. */
  roundDurationSeconds: number;
  endCondition: RoundEndCondition;
}

/** Wire refinement of the design's `FoodMoteView[]`: static motes ride as deltas (docs/ARCHITECTURE.md §4.1). */
export interface FoodDelta {
  /** Every mote when the snapshot is a `game_state`. */
  spawned: FoodMoteView[];
  removedIds: EntityId[];
  /** Every bacterium, every snapshot: they random-walk. */
  moved: MotePositionView[];
}

export interface GameSnapshot {
  tick: number;
  /** The current round's seed; a rematch increments it. */
  seed: number;
  /** 0 at creation, the current tick at a rematch: the HUD derives the world clock from `tick − roundStartTick` (docs/ECOLOGY.md §3.1). */
  roundStartTick: number;
  roundPhase: RoundPhase;
  roundTimeLeftMs: number;
  gelPatches: GelPatchView[];
  cells: CellView[];
  /** Full every snapshot: they drift. */
  dnaFragments: DnaFragmentView[];
  food: FoodDelta;
  /** Built from the join-ordered array. */
  players: Record<string, PlayerProgressView>;
  leaderboard: LeaderboardRow[];
  /** Prediction (docs/ARCHITECTURE.md §5). */
  appliedInputSequenceByPlayer: Record<string, number>;
  /** This broadcast window's effects. */
  effects: GameEffect[];
}

// ===== Generic lobby / player descriptors =====
export interface LobbyPlayerInfo {
  playerId: PlayerId;
  playerName: string;
  avatarIndex: number;
}

export interface LobbyGameInfo {
  gameId: GameId;
  gameName: string;
  players: LobbyPlayerInfo[];
  maxPlayers: number;
  isStarted: boolean;
  creatorId: PlayerId;
}

/**
 * The seven CPU stages of a client frame (docs/RENDERING.md §7), the keys of `renderStagesMs`. Listed
 * beside the report because the server's schema and the client's stage timer must agree on them.
 */
export const RENDER_STAGE = {
  net: 'net',
  cells: 'cells',
  organelles: 'organelles',
  food: 'food',
  effects: 'effects',
  camera: 'camera',
  submit: 'submit',
} as const;
export type RenderStageName = (typeof RENDER_STAGE)[keyof typeof RENDER_STAGE];
/** Every stage in the order the frame runs them; the report carries each key (pinned complete in messages.test.ts). */
export const RENDER_STAGE_NAMES: readonly RenderStageName[] = [
  RENDER_STAGE.net,
  RENDER_STAGE.camera,
  RENDER_STAGE.food,
  RENDER_STAGE.cells,
  RENDER_STAGE.organelles,
  RENDER_STAGE.effects,
  RENDER_STAGE.submit,
];

/** The client's frame-budget report (docs/RENDERING.md §7): rolling p95s over the last frames. */
export interface ClientPerformanceReport {
  fps: number;
  frameTimeAvgMs: number;
  frameTimeP95Ms: number;
  frameTimePeakMs: number;
  heapMb: number | null;
  /** p95 per stage, ms; every `RENDER_STAGE` key present. */
  renderStagesMs: Readonly<Record<RenderStageName, number>>;
  /** GPU time per frame, ms (timer query); `null` when the context has no timer extension. */
  gpuMs: number | null;
  /** GL draw calls in the last frame (docs/RENDERING.md §6). */
  drawCalls: number;
  visibleCells: number;
  visibleMotes: number;
}

// ===== Generic room / lobby view models =====
// Game-agnostic snapshots of server-side state, suitable for MCP/debug views
// and client lobby rendering. The `isStarted` flag is the room lifecycle marker;
// `LobbyGameInfo` (above) is the trimmed form sent over the wire in `lobby_update`.
export interface RoomState {
  gameId: GameId;
  gameName: string;
  creatorId: PlayerId;
  maxPlayers: number;
  isStarted: boolean;
  /** Players currently connected to the room. */
  connectedPlayerIds: PlayerId[];
  /** Players in a disconnect grace window (may reattach before removal). */
  disconnectedPlayerIds: PlayerId[];
  /** Every player ever in the room, in join order. */
  allPlayerIds: PlayerId[];
}

export interface LobbyState {
  /** Active (started) rooms. */
  rooms: RoomState[];
  /** Pending (not-yet-started) games awaiting players. */
  pending: LobbyGameInfo[];
}

// ===== Message type ids =====
// The wire verbs live here as `as const` objects (docs/CODE-STANDARDS.md §2);
// schemas, routers and clients import them instead of repeating string literals.
// Everything game-specific rides `player_input`; there are no game-specific client verbs.
export const CLIENT_MESSAGE_TYPE = {
  joinLobby: 'join_lobby',
  updatePlayerInfo: 'update_player_info',
  createGame: 'create_game',
  joinGame: 'join_game',
  startGame: 'start_game',
  deleteGame: 'delete_game',
  playerInput: 'player_input',
  clientPerformance: 'client_performance',
} as const;

export const SERVER_MESSAGE_TYPE = {
  lobbyUpdate: 'lobby_update',
  gameStarted: 'game_started',
  gameState: 'game_state',
  gameSnapshot: 'game_snapshot',
  playerJoined: 'player_joined',
  playerDisconnected: 'player_disconnected',
  /** After `debug_set_balance`: the live balance every client must predict with (docs/ARCHITECTURE.md §4). */
  balanceUpdated: 'balance_updated',
  error: 'error',
} as const;

// ===== Client -> Server =====
export type ClientMessage =
  | { type: typeof CLIENT_MESSAGE_TYPE.joinLobby; playerName: string; avatarIndex: number }
  | { type: typeof CLIENT_MESSAGE_TYPE.updatePlayerInfo; playerName: string; avatarIndex: number }
  | { type: typeof CLIENT_MESSAGE_TYPE.createGame; gameName: string; config: GameSessionConfig }
  | { type: typeof CLIENT_MESSAGE_TYPE.joinGame; gameId: string }
  | { type: typeof CLIENT_MESSAGE_TYPE.startGame; gameId: string }
  | { type: typeof CLIENT_MESSAGE_TYPE.deleteGame; gameId: string }
  | { type: typeof CLIENT_MESSAGE_TYPE.playerInput; payload: GameInput }
  | { type: typeof CLIENT_MESSAGE_TYPE.clientPerformance; report: ClientPerformanceReport };

// ===== Server -> Client =====
export type ServerMessage =
  | { type: typeof SERVER_MESSAGE_TYPE.lobbyUpdate; games: LobbyGameInfo[] }
  | {
      type: typeof SERVER_MESSAGE_TYPE.gameStarted;
      gameId: GameId;
      playerId: PlayerId;
      playerIds: PlayerId[];
      isHost: boolean;
      config: GameSessionConfig;
    }
  | {
      // Join, late join and reconnect: the full state (`food.spawned` is every mote) plus the
      // balance the server simulates with, so the client predicts with the same numbers.
      type: typeof SERVER_MESSAGE_TYPE.gameState;
      gameId: GameId;
      playerId: PlayerId;
      snapshot: GameSnapshot;
      balance: BalanceConfig;
      config: GameSessionConfig;
      playerIds: PlayerId[];
      avatarAssignments: Record<string, number>;
    }
  | { type: typeof SERVER_MESSAGE_TYPE.gameSnapshot; snapshot: GameSnapshot }
  | { type: typeof SERVER_MESSAGE_TYPE.playerJoined; playerId: PlayerId; avatarIndex: number }
  | { type: typeof SERVER_MESSAGE_TYPE.playerDisconnected; playerId: PlayerId }
  | { type: typeof SERVER_MESSAGE_TYPE.balanceUpdated; balance: BalanceConfig }
  | { type: typeof SERVER_MESSAGE_TYPE.error; message: string };

// Convenience unions for exhaustive handling.
export type ClientMessageType = ClientMessage['type'];
export type ServerMessageType = ServerMessage['type'];
