#!/usr/bin/env bash
# docs-index.sh — generate docs/INDEX.md: every heading of every docs/*.md and docs/*/*.md with its line range and first
# sentence, so a brief can cite "ecology/constants.md §7 (L5–103)" and an agent reads only that range (docs/TEAM.md).
#
#   scripts/docs-index.sh                  # rewrite docs/INDEX.md
#   scripts/docs-index.sh --if-stale       # rewrite it only when --stale-reason names a reason, printing that reason
#   scripts/docs-index.sh --stale-reason   # why the index needs a rewrite: missing, a doc changed since, unformatted
#   scripts/docs-index.sh --install-hooks  # the shared post-checkout / post-merge hooks that run --if-stale
#
# The index is git-ignored and never committed (#407): a committed index conflicted on nearly every back-to-back
# merge. It is generated on demand instead: by scripts/lib/workspace-ready.sh (validate.sh, run.sh, the deploy), by
# scripts/worktree.sh add, and by the git hooks, which live in the common git dir so one install covers every
# worktree. --if-stale and --stale-reason do nothing in a checkout whose .gitignore does not ignore the index (an
# older branch that still commits it), and the hooks run nothing in a checkout without this script.
#
# The index is stale when it is missing, when a doc or a docs directory (a doc added, renamed or deleted) is newer
# than it, or when it was written unformatted and prettier is installed now. A section's range runs from its heading
# to the line before the next heading of the same or a higher level. Headings inside fenced code blocks (``` or ~~~,
# at any indent) are ignored. Output is passed through prettier; without node_modules the generator writes it
# unformatted, marked, and the next --if-stale after an install formats it.
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
docs_dir="$repo_root/docs"
index_relative_path=docs/INDEX.md
index_file="$repo_root/$index_relative_path"
SUMMARY_MAX_CHARS=140
DOCS_DIRECTORY_DEPTH=2 # docs/*.md and docs/*/*.md
UNFORMATTED_MARKER='<!-- docs-index: unformatted, prettier was not installed -->'
HOOK_MARKER='# docs-index hook (scripts/docs-index.sh --install-hooks)'
HOOK_NAMES=(post-checkout post-merge)

index_one_document() {
  local path="$1"
  awk -v max="$SUMMARY_MAX_CHARS" '
    function flush(i) {
      if (count == 0) return
      for (i = 1; i <= count; i++) {
        end = NR
        for (j = i + 1; j <= count; j++) if (level[j] <= level[i]) { end = line[j] - 1; break }
        printf "%s- **%s** (L%d–%d)%s\n", indent[i], title[i], line[i], end, (summary[i] == "" ? "" : ": " summary[i])
      }
    }
    /^[[:space:]]*(```|~~~)/ { fenced = !fenced; next }
    fenced { next }
    /^#{1,6} / {
      count++
      match($0, /^#+/)
      level[count] = RLENGTH
      indent[count] = (level[count] <= 2 ? "" : "  ")
      title[count] = link_text(substr($0, RLENGTH + 2))
      line[count] = NR
      summary[count] = ""
      want = count
      buffer = ""
      next
    }
    want && $0 ~ /^[[:space:]]*$/ { if (buffer != "") finish(); else next }
    want && $0 !~ /^[|>]/ && $0 !~ /^<!--/ && $0 !~ /^[[:space:]]*([-*]|[0-9]+\.) / {
      s = $0
      gsub(/^[[:space:]]+|[[:space:]]+$/, "", s)
      buffer = (buffer == "" ? s : buffer " " s)
      if (match(buffer, /[.!?]( |$)/)) finish()
      next
    }
    want && buffer != "" { finish() }
    function finish() {
      s = buffer
      gsub(/\*\*/, "", s)
      s = link_text(s)
      if (match(s, /[.!?]( |$)/)) s = substr(s, 1, RSTART)
      if (length(s) > max) s = substr(s, 1, max - 1) "…"
      summary[want] = s
      want = 0
      buffer = ""
    }
    # The index keeps the text of a link, not its target: the target is relative to the source file, not to INDEX.md.
    function link_text(s, link) {
      while (match(s, /\[[^]]*\]\([^)]*\)/)) {
        link = substr(s, RSTART, RLENGTH)
        s = substr(s, 1, RSTART - 1) substr(link, 2, index(link, "](") - 2) substr(s, RSTART + RLENGTH)
      }
      return s
    }
    END { flush() }
  ' "$path"
}

generate() {
  echo "# docs/ index"
  echo
  echo "Generated by \`scripts/docs-index.sh\` — do not edit by hand; git-ignored, regenerated on demand. Cite sections as"
  echo "\`FILE.md §heading (Lstart–end)\` and read only that line range (\`sed -n 'start,endp' docs/FILE.md\`)."
  echo
  local path name
  for path in "$docs_dir"/*.md "$docs_dir"/*/*.md; do
    name="${path#"$docs_dir"/}"
    [[ "$name" == "INDEX.md" ]] && continue
    echo "## $name ($(wc -l < "$path") lines)"
    echo
    index_one_document "$path"
    echo
  done
}

have_prettier() { (cd "$repo_root" && command -v pnpm >/dev/null && [[ -d node_modules ]]); }

# Prettier skips a path .gitignore names, and the index is git-ignored: read .prettierignore alone.
format() {
  if have_prettier; then
    (cd "$repo_root" && pnpm --silent exec prettier --ignore-path .prettierignore --stdin-filepath "$index_relative_path")
  else
    cat
    printf '\n%s\n' "$UNFORMATTED_MARKER"
  fi
}

# Written in place, never renamed over the old file: a rename touches docs/, which would then be newer than the index.
write_index() {
  local content
  content="$(generate | format)"
  printf '%s\n' "$content" > "$index_file"
  echo "wrote $index_file ($(grep -c '^ *- ' "$index_file") sections)"
}

is_index_ignored() { git -C "$repo_root" check-ignore -q "$index_relative_path" 2>/dev/null; }

stale_reason() {
  is_index_ignored || return 0
  if [[ ! -f "$index_file" ]]; then
    echo "$index_relative_path is missing"
    return 0
  fi
  local newer
  newer="$(find "$docs_dir" -maxdepth "$DOCS_DIRECTORY_DEPTH" \( -type d -o -name '*.md' \) ! -path "$index_file" \
    -newer "$index_file" -print -quit)"
  if [[ -n "$newer" ]]; then
    echo "${newer#"$repo_root"/} changed since $index_relative_path was written"
  elif have_prettier && grep -qF -- "$UNFORMATTED_MARKER" "$index_file"; then
    echo "$index_relative_path was written without prettier, which is installed now"
  fi
}

hook_body() {
  cat <<HOOK
#!/usr/bin/env bash
$HOOK_MARKER
# Refreshes the git-ignored docs/INDEX.md of the checkout git just updated; never fails the git command.
root="\$(git rev-parse --show-toplevel 2>/dev/null)" || exit 0
[[ -x "\$root/scripts/docs-index.sh" ]] && git -C "\$root" check-ignore -q $index_relative_path 2>/dev/null || exit 0
"\$root/scripts/docs-index.sh" --if-stale >/dev/null 2>&1 || true
HOOK
}

# Writes each hook that is missing or already ours; a foreign hook of the same name is left alone, with a note.
install_hooks() {
  local hooks_dir name hook
  hooks_dir="$(cd "$repo_root" && git rev-parse --path-format=absolute --git-path hooks)"
  mkdir -p "$hooks_dir"
  for name in "${HOOK_NAMES[@]}"; do
    hook="$hooks_dir/$name"
    if [[ -e "$hook" ]] && ! grep -qF -- "$HOOK_MARKER" "$hook"; then
      echo "docs-index: $hook exists and is not ours; left alone"
      continue
    fi
    [[ -e "$hook" ]] && [[ "$(cat "$hook")" == "$(hook_body)" ]] && continue
    hook_body > "$hook"
    chmod +x "$hook"
    echo "docs-index: installed $hook"
  done
}

case "${1:-}" in
  "") write_index ;;
  --stale-reason) stale_reason ;;
  --if-stale)
    reason="$(stale_reason)"
    [[ -z "$reason" ]] || { echo "docs index: $reason"; write_index; }
    ;;
  --install-hooks) install_hooks ;;
  *) sed -n '5,8p' "${BASH_SOURCE[0]}"; exit 1 ;;
esac
