#!/usr/bin/env bash
# docs-index.sh — generate docs/INDEX.md: every heading of every docs/*.md and docs/*/*.md with its line range and first
# sentence, so a brief can cite "ecology/constants.md §7 (L5–103)" and an agent reads only that range (docs/TEAM.md).
#
#   scripts/docs-index.sh            # rewrite docs/INDEX.md
#   scripts/docs-index.sh --check    # exit 1 when the committed docs/INDEX.md is stale (run by ./validate.sh lint)
#
# A section's range runs from its heading to the line before the next heading of the same or a higher level.
# Headings inside fenced code blocks (``` or ~~~, at any indent) are ignored. Output is passed through prettier so the
# committed file matches `prettier --check`; without node_modules the generator writes unformatted output and --check
# reports that it could not check rather than a false stale.
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
docs_dir="$repo_root/docs"
index_file="$docs_dir/INDEX.md"
SUMMARY_MAX_CHARS=140

index_one_document() {
  local path="$1"
  awk -v max="$SUMMARY_MAX_CHARS" '
    function flush(i) {
      if (count == 0) return
      for (i = 1; i <= count; i++) {
        end = NR
        for (j = i + 1; j <= count; j++) if (level[j] <= level[i]) { end = line[j] - 1; break }
        printf "%s- **%s** (L%d–%d)%s\n", indent[i], title[i], line[i], end, (summary[i] == "" ? "" : ": " summary[i])
      }
    }
    /^[[:space:]]*(```|~~~)/ { fenced = !fenced; next }
    fenced { next }
    /^#{1,6} / {
      count++
      match($0, /^#+/)
      level[count] = RLENGTH
      indent[count] = (level[count] <= 2 ? "" : "  ")
      title[count] = link_text(substr($0, RLENGTH + 2))
      line[count] = NR
      summary[count] = ""
      want = count
      buffer = ""
      next
    }
    want && $0 ~ /^[[:space:]]*$/ { if (buffer != "") finish(); else next }
    want && $0 !~ /^[|>]/ && $0 !~ /^<!--/ && $0 !~ /^[[:space:]]*([-*]|[0-9]+\.) / {
      s = $0
      gsub(/^[[:space:]]+|[[:space:]]+$/, "", s)
      buffer = (buffer == "" ? s : buffer " " s)
      if (match(buffer, /[.!?]( |$)/)) finish()
      next
    }
    want && buffer != "" { finish() }
    function finish() {
      s = buffer
      gsub(/\*\*/, "", s)
      s = link_text(s)
      if (match(s, /[.!?]( |$)/)) s = substr(s, 1, RSTART)
      if (length(s) > max) s = substr(s, 1, max - 1) "…"
      summary[want] = s
      want = 0
      buffer = ""
    }
    # The index keeps the text of a link, not its target: the target is relative to the source file, not to INDEX.md.
    function link_text(s, link) {
      while (match(s, /\[[^]]*\]\([^)]*\)/)) {
        link = substr(s, RSTART, RLENGTH)
        s = substr(s, 1, RSTART - 1) substr(link, 2, index(link, "](") - 2) substr(s, RSTART + RLENGTH)
      }
      return s
    }
    END { flush() }
  ' "$path"
}

generate() {
  echo "# docs/ index"
  echo
  echo "Generated by \`scripts/docs-index.sh\` — do not edit by hand. Cite sections as \`FILE.md §heading (Lstart–end)\`"
  echo "and read only that line range (\`sed -n 'start,endp' docs/FILE.md\`). Regenerate after editing any doc; \`./validate.sh lint\` checks it."
  echo
  local path name
  for path in "$docs_dir"/*.md "$docs_dir"/*/*.md; do
    name="${path#"$docs_dir"/}"
    [[ "$name" == "INDEX.md" ]] && continue
    echo "## $name ($(wc -l < "$path") lines)"
    echo
    index_one_document "$path"
    echo
  done
}

have_prettier() { (cd "$repo_root" && command -v pnpm >/dev/null && [[ -d node_modules ]]); }

format() {
  if have_prettier; then
    (cd "$repo_root" && pnpm --silent exec prettier --stdin-filepath docs/INDEX.md)
  else
    cat
  fi
}

if [[ "${1:-}" == "--check" ]]; then
  if ! have_prettier; then
    echo "docs/INDEX.md freshness not checked: prettier is not installed here (run pnpm install)" >&2
    exit 0
  fi
  if diff -u "$index_file" <(generate | format) >/dev/null 2>&1; then
    echo "docs/INDEX.md is up to date"
  else
    echo "docs/INDEX.md is stale: run scripts/docs-index.sh and commit the result" >&2
    exit 1
  fi
else
  generate | format > "$index_file"
  echo "wrote $index_file ($(grep -c '^ *- ' "$index_file") sections)"
fi
